services:
  db:
    image: postgres
    container_name: db-postgres
    restart: always
    ports: 
      - 15432:5432
    volumes:
      - ./dbs/postgres-data:/var/lib/postgresql/data
    env_file:
      - db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maindb"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth:
    image: express-auth-backend
    build:
      context: ./auth
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /var/www/apps/auth/node_modules
    env_file:
      - ./auth/.env.prod
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  project:
    image: express-project-backend
    build:
      context: ./project
    restart: always
    ports:
      - 8001:8001
    volumes:
      - /var/www/apps/project/node_modules
    env_file:
      - ./project/.env.prod
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  resume:
    image: express-resume-backend
    build:
      context: ./resume
    restart: always
    ports:
      - 8002:8002
    volumes:
      - /var/www/apps/resume/node_modules
    env_file:
      - ./resume/.env.prod
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  request:
    image: express-request-backend
    build:
      context: ./request
    restart: always
    ports:
      - 8003:8003
    volumes:
      - /var/www/apps/request/node_modules
    env_file:
      - ./request/.env.prod
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
    driver: local