name: CI/CD Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      job_to_run:
        description: 'Выберите джоб для запуска'
        required: true
        type: choice
        options:
          - rebuild
          - deploy
          - restart

jobs:
  build-manual:
    name: Build Manual
    runs-on: self-hosted
    if: github.event.inputs.job_to_run == 'rebuild'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Copy files to destination
        run: rsync -av --progress ./ /var/www/apps/backend-study-project/
        
      - name: Build Docker containers
        run: docker compose -f /var/www/apps/backend-study-project/docker-compose.yml build

  start-manual:
    name: Start Manual
    needs: build-manual
    runs-on: self-hosted
    if: github.event.inputs.job_to_run == 'deploy'
    steps:
      - name: Start services
        run: docker compose -f /var/www/apps/backend-study-project/docker-compose.yml up -d

  restart-manual:
    name: Restart Manual
    runs-on: self-hosted
    if: github.event.inputs.job_to_run == 'restart'
    steps:
      - name: Restart services
        run: docker compose -f /var/www/apps/backend-study-project/docker-compose.yml restart

  deployment:
    name: Deployment
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Copy files to destination
        run: rsync -av --progress ./ /var/www/apps/backend-study-project/
        
      - name: Build services
        run: docker compose -f /var/www/apps/backend-study-project/docker-compose.yml build
        
      - name: Deploy services
        run: docker compose -f /var/www/apps/backend-study-project/docker-compose.yml up -d --force-recreate
