name: CI/CD Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-manual:
    name: Build Manual
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Copy files to destination
        run: rsync -av --progress ./ /var/www/apps/backend-study-project/
        
      - name: Build Docker containers
        run: docker compose -f /var/www/apps/backend-study-project/docker-compose.yml build

    if: github.event_name == 'workflow_dispatch'

  start-manual:
    name: Start Manual
    needs: build-manual
    runs-on: self-hosted
    steps:
      - name: Start services
        run: docker compose -f /var/www/apps/backend-study-project/docker-compose.yml up -d

    if: github.event_name == 'workflow_dispatch'

  restart-manual:
    name: Restart Manual
    runs-on: self-hosted
    steps:
      - name: Restart services
        run: docker compose -f /var/www/apps/backend-study-project/docker-compose.yml restart

    if: github.event_name == 'workflow_dispatch'

  deployment:
    name: Deployment
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Copy files to destination
        run: rsync -av --progress ./ /var/www/apps/backend-study-project/
        
      - name: Build services
        run: docker compose -f /var/www/apps/backend-study-project/docker-compose.yml build
        
      - name: Deploy services
        run: docker compose -f /var/www/apps/backend-study-project/docker-compose.yml up -d --force-recreate
